Feature/user/login
DobocanDarius/InternshipProject-2 pull request #7
Opened 2023-08-23 06:14 UTC by DobocanDarius

2023-08-23 07:17 UTC, iiusan requested changes

2023-08-23 07:17 UTC, iiusan commented on InternshipProject#2/Controllers/UserController.cs
> +using Microsoft.EntityFrameworkCore;
this is not SOLID!!!
why do you have references to entity framework?

2023-08-23 07:17 UTC, iiusan commented on InternshipProject#2/Controllers/UserController.cs
> +        private readonly PasswordHash _hash;
where is this used?

2023-08-23 07:17 UTC, iiusan commented on InternshipProject#2/Helpers/Token.cs
> +public class Token
looks like this class it's a model. needs a rename

2023-08-23 07:17 UTC, iiusan commented on InternshipProject#2/Manager/UserManager.cs
> +    private readonly PasswordHash _hash;
where is this used?

2023-08-23 07:17 UTC, iiusan commented on RequestResponseModels/User/Request/LoginRequest.cs
>      public string Password { get; set; } = null!;
without null!

2023-08-23 07:17 UTC, iiusan commented on RequestResponseModels/User/Request/UserRequest.cs
> +    public class UserRequest
empty class

2023-08-23 07:17 UTC, iiusan commented on RequestResponseModels/User/Response/UserResponse.cs
> +public class UserResponse
empty class

2023-08-23 12:25 UTC, hunorszekely requested changes

2023-08-23 12:25 UTC, hunorszekely commented on RequestResponseModels/User/Response/LoginResponse.cs
> +    public IEnumerable<LoginRequest> Users { get; set; }
Not sure why are you returning this... Why is it a collection?

2023-08-23 12:25 UTC, hunorszekely commented on InternshipProject#2/Manager/UserManager.cs
> +            var loginResponse = map.Map<LoginResponse>(foundUser);
Have you tested this mapping? It cannot map the user into the LoginResponse.

2023-08-23 12:25 UTC, hunorszekely commented on InternshipProject#2/Manager/UserManager.cs
> +            loginResponse.Token = _token.Generate(foundUser);
If you are using AutoMapper, all the properties should be mapped inside of it.

2023-08-23 12:25 UTC, hunorszekely commented on InternshipProject#2/Program.cs
> +
Pay attention to empty lines as well.

2023-08-24 06:44 UTC, hunorszekely approved these changes

2023-08-24 07:16 UTC, merged